# 数据源配置
spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://www.zteiot.cn:3306/ziyan?useUnicode=true&characterEncoding=utf8
        username: ziyan
        password: 87678540
        initialSize: 5
        minIdle: 5
        maxActive: 10
        maxWait: 60000
    ## Redis 配置
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password:
        timeout: 0

        pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0

    ##FREEMARKER (FreeMarkerAutoConfiguration)
    freemarker:
        allow-request-override: false
        cache: true
        check-template-location: true
        charset: UTF-8
        content-type: text/html
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: false
        suffix:
    #prefix:
    #request-context-attribute:
    #settings.*:
    #template-loader-path: classpath:/templates/ #comma-separated list
    #view-names:  # whitelist of view names that can be resolved

# Mybatis 配置
mybatis:
    typeAliasesPackage: com.ziyan.domain
    mapperLocations: classpath:com.ziyan.dao/*.xml