server:
    port: 8080

spring:
    application:
        name: nest

    # 数据源配置
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/ziyan?useUnicode=true&characterEncoding=utf8
        username: root
        password: 123456
        initialSize: 5
        minIdle: 5
        maxActive: 10
        maxWait: 60000

    thymeleaf:
            mode: LEGACYHTML5

# Mybatis 配置
mybatis:
    typeAliasesPackage: com.ziyan.domain
    mapperLocations: classpath:com.ziyan.dao/*.xml
# Redis 配置
redis:
    host: localhost
    port: 6379
    password:
    pool:
        max-idle: 10
        min-idle: 0
        max-active: 16
        max-wait: -1
